spring:
  datasource:
    url: jdbc:h2:C:\Users\logonrmlocal\Desktop\cervejaria-batch-tasklet;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap

file:
  path: C:\Users\logonrmlocal\Desktop\cervejaria-batch-tasklet\banco.batch.mv.db
  input: classpath:pessoa.txt
